name: test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  fmt:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Restore Go module cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check go fmt
        run: |
          OUTPUT=$(gofmt -l .)
          if [ -n "$OUTPUT" ]; then
            echo "Go files are not formatted. Please run 'gofmt -w .':"
            echo "$OUTPUT"
            exit 1
          fi

  vet:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Restore Go module cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run go vet
        run: go vet ./...

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Restore Go module cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test with the Go CLI
        run: go test -v ./...

      - name: Display Docker logs on failure
        if: failure()
        run: |
          echo "Listing all Docker containers..."
          docker ps -a
          echo "Attempting to display logs for all containers..."
          for id in $(docker ps -aq); do
            echo "Logs for container $id:"
            docker logs $id || echo "Failed to get logs for container $id"
            echo "\n---\n"
          done
      
  govulncheck_job:
      needs: setup
      runs-on: ubuntu-latest
      name: Run govulncheck
      steps:
        - id: govulncheck
          uses: golang/govulncheck-action@v1
          with:
            go-version-input: 1.24
            go-package: ./...