name: Test & SAST

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev'
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  Test_and_SAST:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Init go mod (only if not present)
        run: |
          if [ ! -f go.mod ]; then
            go mod init vault-sync
          else
            echo "go.mod already exists, skipping go mod init"
          fi

      - name: Install dependencies
        run: go mod tidy
        
      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v ./...

      - name: Display Docker logs on failure
        if: failure()
        run: |
          echo "Listing all Docker containers..."
          docker ps -a
          echo "Attempting to display logs for all containers..."
          for id in $(docker ps -aq); do
            echo "Logs for container $id:"
            docker logs $id || echo "Failed to get logs for container $id"
            echo "\n---\n"
          done
      
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck (Go security vulnerability scan)
        run: govulncheck ./...