# name: Test & SAST

# on:
#   push:
#     branches:
#       - 'v[0-9]+.[0-9]+.[0-9]+-dev'
#   pull_request:
#     branches:
#       - 'v[0-9]+.[0-9]+.[0-9]+-dev'
#       - 'v[0-9]+.[0-9]+.[0-9]+'

# jobs:
#   test:
#     runs-on: ubuntu-22.04
#     steps:

#       - uses: actions/checkout@v4

#       - name: Set up Go 1.24
#         uses: actions/setup-go@v5
#         with:
#           go-version: 1.24

#       - name: Cache Go modules
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.cache/go-build
#             ~/go/pkg/mod
#           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#           restore-keys: |
#             ${{ runner.os }}-go-

#       - name: Install dependencies
#         run: go mod download

#       - name: Run tests
#         run: go test ./...

#       - name: Run SAST (golangci-lint)
#         uses: golangci/golangci-lint-action@v4
#         with:
#           version: v1.59.1
#           args: --timeout=5m

#       - name: Run govulncheck (Go security vulnerability scan)
#         uses: golang/govulncheck-action@v1
#         with:
#           go-version-input: 1.24
